using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using PhotoAlbum.Logic.Models;

namespace PhotoAlbum.Logic.Interfaces
{
    /// <inheritdoc />
    /// <summary>
    ///     Interface IPhotoAlbumClient
    /// </summary>
    /// <autogeneratedoc />
    public interface IPhotoAlbumClient : IDisposable
    {
        /// <summary>
        ///     Loads the album data.
        /// </summary>
        /// <param name="albumId">The album identifier.</param>
        /// <returns>Task&lt;IEnumerable&lt;AlbumModel&gt;&gt;.</returns>
        /// <remarks>This returns an empty collection if nothing is found</remarks>
        Task<IEnumerable<AlbumModel>> GetAlbums(string albumId = null);
    }
}