using System;
using System.Collections.Generic;

namespace PhotoAlbum.Logic.Models
{
    /// <summary>
    ///     Class AlbumModel.
    /// </summary>
    /// <autogeneratedoc />
    public class AlbumModel
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="AlbumModel" /> class.
        /// </summary>
        /// <autogeneratedoc />
        public AlbumModel()
        {
            Photos = new List<PhotoModel>();
        }

        /// <summary>
        ///     Gets or sets the album identifier.
        /// </summary>
        /// <value>The album identifier.</value>
        /// <autogeneratedoc />
        public string AlbumId { get; set; }

        /// <summary>
        ///     Gets or sets the fetched date.
        /// </summary>
        /// <value>The fetched date.</value>
        /// <autogeneratedoc />
        public DateTimeOffset FetchedDate { get; set; }

        /// <summary>
        ///     Gets or sets the photos.
        /// </summary>
        /// <value>The photos.</value>
        /// <autogeneratedoc />
        public List<PhotoModel> Photos { get; set; }
    }
}