namespace PhotoAlbum.Logic.Models
{
    /// <summary>
    ///     Class PhotoModel.
    /// </summary>
    /// <autogeneratedoc />
    public class PhotoModel
    {
        /// <summary>
        ///     Gets or sets the album identifier.
        /// </summary>
        /// <value>The album identifier.</value>
        /// <autogeneratedoc />
        public string AlbumId { get; set; }

        /// <summary>
        ///     Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        /// <autogeneratedoc />
        public string Id { get; set; }

        /// <summary>
        ///     Gets or sets the thumbnail URL.
        /// </summary>
        /// <value>The thumbnail URL.</value>
        /// <autogeneratedoc />
        public string ThumbnailUrl { get; set; }

        /// <summary>
        ///     Gets or sets the title.
        /// </summary>
        /// <value>The title.</value>
        /// <autogeneratedoc />
        public string Title { get; set; }

        /// <summary>
        ///     Gets or sets the URL.
        /// </summary>
        /// <value>The URL.</value>
        /// <autogeneratedoc />
        public string Url { get; set; }
    }
}